services:

  app:
    build:
      context: ./../services
      dockerfile: ./../services/Dockerfile
    # restart: always
    ports:
      - "8080:80"
    environment:
      DSN: "host=app-postgres port=5432 user=postgres password=password dbname=pipecraft sslmode=disable timezone=UTC connect_timeout=5"
    depends_on:
      - migrate
      - redis

  app-postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pipecraft
    volumes: 
      - ./db-data/app-postgres/:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./../services/migrations:/migrations
    entrypoint: ["migrate"]
    command: ["-path", "/migrations", "-database", "postgres://postgres:password@app-postgres:5432/pipecraft?sslmode=disable", "up"]
    depends_on:
      - app-postgres

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis:/data