services:
  app:
    build:
      context: ./../services
      dockerfile: ./../services/Dockerfile
    # restart: always
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      DSN: "host=app-postgres port=5432 user=postgres password=password dbname=pipecraft sslmode=disable timezone=UTC connect_timeout=5"

  app-postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pipecraft
    volumes: 
      - ./db-data/app-postgres/:/var/lib/postgresql/data

